Desktop version
ginabeki/My-portfolio pull request #5
Opened 2022-09-29 21:08 UTC by ginabeki

## Building desktop version

I did the following in this project:-
- Updated font size to match desktop version design
- Used grid layout to align items on the page
- Updated HTML markup to adjust some changes on the desktop version
- Checked for lint errors and fixed the errors
- Ensured the website is responsive

2022-09-29 22:02 UTC, levy002 requested changes
## Hello @ginabeki   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 22:02 UTC, levy002 commented on styles.css
> +  }
- [ ] Kindly make sure to add all background images to the contact section in order to meet the provided design :wink: 

    - ### Your design
   ![image](https://user-images.githubusercontent.com/87197412/193150033-701bb083-802a-46d9-8c87-2f696be1eac4.png)


   - ### Figma design
   ![image](https://user-images.githubusercontent.com/87197412/193149980-6dab7e35-b263-4c09-8aad-1c91f767f1bb.png)

2022-09-30 06:42 UTC, ginabeki commented on index.html
> +      </div>
Fixed

2022-09-30 06:59 UTC, ginabeki commented on index.html
> +        </button>
Fixed

2022-09-30 09:09 UTC, ginabeki commented on index.html
>        </p>
Doned

2022-09-30 09:12 UTC, levy002 commented
Thank you @ginabeki for considering all suggested changes. Kindly feel free to go ahead and submit your PR for another review. :wink:

2022-09-30 10:03 UTC, ginabeki commented on styles.css
> +  }
Done

2022-09-30 10:15 UTC, ginabeki commented
## Revision
Here are some of the things I added in regards to the previous feedback:-
- Added the required text color to the footer section
- Changed the width of the buttons to match the Figma design
- Changed the typography of the contact section paragraph to match the design.
- Added a missing background image to the contact section


#### Thank you for taking your time to review my work 🙌

2022-09-30 10:33 UTC, nedjwab approved these changes
# 🟢 Project Approved! 🏆

## Hi @ginabeki    👋

Your project is complete! ✔️ 🏁

Your code was very professional 💯

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉

 
## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors.
- ✔good design 🔥🔥
- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 10:41 UTC, merged